### ISSUE TITLE
IE11 Support

### ISSUE THREAD

**Issue by johnpernock** [pozil/sfdc-ui-lookup#6]
Ive been developing a couple components and implemented the lookup on them. Our client asked for us to support IE11 and for some reason the Components fail when used in IE11, Ive been trying to do a work around and didn't know if you had seen any weird behaviors in IE11?

**Comment by pozil** [comment]
Hi @johnpernock, I don't have a Windows machine with IE11 so I am going to have a hard time to replicate this.
Do you have any info about the error?

**Comment by adammfalk** [comment]
Hoping this helps:
I ran into an issue on IE11 yesterday, and it turns out that arrow functions in javascript aren't supported in IE11. I replaced that in the onblur handling with an embedded function and it started working.

`const blurTimeout = window.setTimeout($A.getCallback(function(){...}))`

**Comment by johnpernock** [comment]
Oh interesting! Sorry, with the holiday I got a little side tracked. Let me update the version I have running and get back to you. I do my dev on a Mac so I have to find my spare windows PC to test.

**Comment by pozil** [comment]
Thanks for pointing this out @adammfalk, arrow functions are definitely a blocker on IE11:
https://caniuse.com/#feat=arrow-functions

This is rather problematic because I've used arrow functions in this component and in its dependency: the [Server Action Service](https://github.com/pozil/server-action-service).
I've created an [issue](https://github.com/pozil/server-action-service/issues/4) on the service. We'll need to fix that and the lookup component.

**Comment by pozil** [comment]
Actually, disregard my comments about the service, I am not using it in this component.
I will release a new version without the arrow functions.

**Comment by pozil** [comment]
Fixed in v1.2.1.

Thanks @johnpernock and @adammfalk.
